language: python
python:
    - 2.7
    - 3.6

sudo: false

install:
    - pip install -r dev-requirements.txt -r requirements.txt
    - pip install -e .

script:
    - "grepme -l <<< $GREPME_API_KEY" # login
    - "test/pre-commit"
